### ISSUE TITLE
sorting the results by rank field

### ISSUE THREAD

**Issue by gedigerivijay** [usc-isi-i2/dig-etl-engine#109]
Hi,

I got the project working with my sample json file. I have a field called 'rank' by which I want to sort my results. I see there is option for Sort with two options - By frequency and Alphabetical. Rank in my case is a number. Can you please help me on how to enable sort by a numerical field with larger rank first? Here's the KG results:

![image](https://user-images.githubusercontent.com/8144220/33247494-54507150-d2d3-11e7-8213-cf4c8e12865f.png)

I have also uploaded by json input file in.jl and supplemental json file that has extraction rules. 

[data.zip](https://github.com/usc-isi-i2/dig-etl-engine/files/1504479/data.zip)

Only 3 fields needed to be added - description, name and rank. Appreciate the help. Thank you
@szeke @GreatYYX 
- Vijay

**Comment by szeke** [comment]
@jasonslepicka please see if you can assist @gedigerivijay with sorting results by rank, a field in the KG objects.

**Comment by jasonslepicka** [comment]
@szeke sorting by field is on my to do list this week.  however, the sorting options @gedigerivijay pointed out are only for sorting the aggregation terms.   sorting search result documents won't be possible without changes in the front end from @ThomasSchellenbergNextCentury.

**Comment by gedigerivijay** [comment]
Thank you Professor @szeke .
Hi @jasonslepicka, thanks for the response. Do you have a estimated date of completion? We have project presentation this Friday, and it would be great if we can get some help before that. Thanks.

**Comment by szeke** [comment]
Ok. Will discuss with Thomas to see how big a change it is to the GUI. 

@jasonslepicka, is the idea that we can pass in a field for sorting, so Thomas needs to show a menu of fields. He would get them from MyDig where we would mark the fields that can be used for sorting. 

If we want to sort on a numeric field, it would need to be indexed as a number, correct? That is another change as we need to add number to the dig types

**Comment by jasonslepicka** [comment]
@szeke, yes.  the gui should show a menu of fields and an asc/desc option.  the gui should translate the chosen field in the interface into a variable in the sparql query. the syntax of order-by for the point-fact is the same as the one used already for aggregation queries, but this new field should not affect the generated sparql / existing behavior of order-by for aggregation queries. 

it's worth noting that even though elasticsearch allows you to specify multiple fields in the sort order, there's no way at the moment to combine the values from multiple fields in to the same field to sort on.  that is, if we have dates in other method and inferlink, if i choose to sort by inferlink dates then other method dates, it will first sort on the inferlink dates and then sort the documents on the same date by the other method dates.  because of this, we can only sort on one field at a time, so i'm only sorting on the high confidence keys.  because they're multivalue, i'm also having elasticsearch sort only on the max value a given document has for the field for descending and the min value for ascending.  

also, yes, we need to change the mapping.  with the exception of dates, we force everything in the mapping to be strings which means those numbers will be lexicographically sorted.

**Comment by jasonslepicka** [comment]
@ThomasSchellenbergNextCentury It's my understanding that we'd like to have elasticsearch sort by any of the fields the document.  In the gui, the user should be able to select one of the fields `postingdate`, `rank`, etc and the gui will generate an order-by for the appropriate sparql variable that corresponds to that gui field.   Pinpoint will use the order-by in the sparql query to tell elasticsearch to return documents according to the document field that `postingdate` maps to.  

Elasticsearch can return a score if you want, or rank documents by the field and then by score, but elasticsearch by default won't score documents if you rank by a field value.

**Comment by jasonslepicka** [comment]
Hopefully this means you won't have to do any additional sorting in the gui, just display the results as elasticsearch returns them.

**Comment by ThomasSchellenbergNextCentury** [comment]
@jasonslepicka How does this work for anything other than Rank or Posting Date (like Telephone Number or City)?

**Comment by jasonslepicka** [comment]
@ThomasSchellenbergNextCentury  When translating the sparql query, pinpoint isn't going to make a value judgment on the chosen field.  It's just going to add a sort clause because Elasticsearch can sort lexicographically on the high confidence keys for Telephone Number or City. 

I'm not saying that sorting on those or any other available field will be particularly useful, especially when there are millions of results and no further ranking by relevance.  It's probably important to limit the fields in the GUI somehow to a meaningful subset so users can't pick a sort order that doesn't make sense.  I'm not sure what that subset is.  We can start with date and numeric type fields defined by mydig first.

**Comment by ThomasSchellenbergNextCentury** [comment]
@jasonslepicka Does order-by work correctly for dates?  For example, will the following clause order the dates as dates (chronologically) or as strings (alphabetically)?
```
            "order-by": {
                "values": [
                    {
                        "variable": "?posting_date",
                        "order": "asc"
                    }
                ]
            }
```

**Comment by jasonslepicka** [comment]
@ThomasSchellenbergNextCentury It's my understanding that the Elasticsearch sort option will respect whatever type is in the field it will sort on.  That said, I'm only ever sorting on the high confidence keys, i.e. `indexed.posting_date.high_confidence_keys`, field that gets generated, which is represented in the mapping as: 

```
"high_confidence_keys" : {
                    "type" : "string",
                    "index" : "not_analyzed"
}
``` 

For well defined ISO date strings, I don't think there's going to be a difference in sort order between the string representation and the actual date.  Are you seeing something inconsistent?  I should mention that since posting date (and other fields) can be multi valued, I have to specify a sort order based on those multi valued fields.  https://github.com/usc-isi-i2/dig-sandpaper/blob/master/digsandpaper/coarse/generate/query_compiler_component.py#L359

**Comment by ThomasSchellenbergNextCentury** [comment]
@jasonslepicka I think sorting by date is not working.  Here is a query I sent to `http://10.3.2.82:9876/search/coarse`:
```
{"SPARQL":{"group-by":{"limit":5,"offset":0},"order-by":{"values":[{"order":"desc","variable":"?posting_date"}]},"select":{"variables":[{"type":"simple","variable":"?ad"}]},"where":{"clauses":[{"constraint":"jessica","isOptional":false,"predicate":"name"}],"filters":[],"type":"Ad","variable":"?ad"}},"type":"Point Fact"}
```
The date of the first result is `Feb 25 2017`, while the second is `March 2 2017` and the third is `Feb 10 2017`.  It's not sorted.  In fact, it looks like the results are in the same order if I remove the `order-by` clause.

**Comment by ThomasSchellenbergNextCentury** [comment]
@jasonslepicka Any updates?

**Comment by jasonslepicka** [comment]
@ThomasSchellenbergNextCentury can we close this? it looks like sorting is working now in production.

**Comment by ThomasSchellenbergNextCentury** [comment]
@jasonslepicka Yes, you can close it.

**Comment by saggu** [comment]
Closing this.
