### ISSUE TITLE
Add Number type to the list of supported types in myDIG

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/dig-etl-engine#159]
When a field is of type `Number`, several things must happen:

- [ ] The ES mapping file should define the field as containing an `double` or some other form of generic number that accepts many different number formats.
- [ ] ETK must post-process the extractions into this field to ensure that the values are numbers. To do this second step, ETK should remove all non-number characters at the beginning until the first digit, and the end of the string, backwards until the last digit, and then try to parse the remaining as a number. If it is a number, use it, otherwise toss the value

The idea of removing leading and trailing non-number is to accept numbers that have units, such as `$120.0` or `25 days`

**Comment by szeke** [comment]
Assigning to @GreatYYX to add support in myDIG (backend and menu), @jasonslepicka for the mapping file, and @saggu to write the post-process in ETK

**Comment by jasonslepicka** [comment]
Pinpoint had the ability to generating mappings for mydig config fields with number types. 
https://github.com/usc-isi-i2/dig-sandpaper/commit/6f56448b1cba32740c085a08fdf4d265c5234435

This adds support for `number` since it's not specifically an elasticsearch type.  `number` will become `double` in the generated elasticsearch mapping.
https://github.com/usc-isi-i2/dig-sandpaper/commit/dce66007872beb1e49a2acfaca6fb6bb2dc9be81

This release should have support for it. 
https://github.com/usc-isi-i2/dig-sandpaper/releases/tag/0.1.4-r059

**Comment by GreatYYX** [comment]
added type number to myDIG GUI and backend
