### ISSUE TITLE
The pinpoints in projects revert to a default index after the dockers get redeployed

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/dig-etl-engine#26]
This morning I opened my SEC project, went to the DIG GUI and it was showing HT pages. I had to rebuild the index to correct the problem. 

Redeployment of dockers should not cause pinpoints to stay misconfigured until the user configures them again.

**Comment by GreatYYX** [comment]
It's the bug in DIG UI, I asked Thomas to update it (see dig-ui channel). The reason causes this is: Originally, one project associated with one sandpaper instance, so frontend requested sandpaper without any project (index) information. Then now sandpaper supports multi projects, but DIG UI still sends requests without project info, in this case, sandpaper queries the result in the latest index re-configured (for backward compatibility). This problem is there since we have new sandpaper, but we haven't noticed it until myDIG had sandpaper auto re-configuration.
Now if you need to test a project, ask me or Amandeep to manually re-configure index to it, you don't need to rebuild kg every time.

**Comment by szeke** [comment]
is this fixed?
