### ISSUE TITLE
Failure to import museum data

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/dig-etl-engine#56]
I upload a `jl` file with 10 records and they don't get imported. The `tmp` file has data, but the corresponding directory is empty.

If the file is invalid, there should be an error message.

**Comment by szeke** [comment]
Attaching file I am trying to upload to myDIG
[museum-10t.jl.zip](https://github.com/usc-isi-i2/dig-etl-engine/files/1414472/museum-10t.jl.zip)

**Comment by GreatYYX** [comment]
@szeke Because file validation and building catalog are asynchronous tasks, GUI can not get response of status in that file upload http connection. I am going to implement a query for fetching task status.
But for this particular dataset, "doc_id" ("_id") is missing, ACHE doesn't follow the format of CDR v3.1.

**Comment by szeke** [comment]
Runqi sent a fixed file
